name: Local Config
version: 1.0.0
schema: v1

models:
  - name: NVIDIA Nemotron 3 Super (Free)
    provider: openrouter
    model: nvidia/nemotron-3-super-120b-a12b:free
    apiBase: https://openrouter.ai/api/v1
    apiKey: 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