/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiWorkspaceRouteImport } from './routes/ai-workspace'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as ExecutiveDashboardRouteImport } from './routes/executive-dashboard'
import { Route as FilesRouteImport } from './routes/files'
import { Route as GameDevRouteImport } from './routes/game-dev'
import { Route as MilestonesRouteImport } from './routes/milestones'
import { Route as ProjectsPipelineRouteImport } from './routes/projects-pipeline'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as WebsiteRouteImport } from './routes/website'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiWorkspaceRoute = AiWorkspaceRouteImport.update({
  id: '/ai-workspace',
  path: '/ai-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveDashboardRoute = ExecutiveDashboardRouteImport.update({
  id: '/executive-dashboard',
  path: '/executive-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const GameDevRoute = GameDevRouteImport.update({
  id: '/game-dev',
  path: '/game-dev',
  getParentRoute: () => rootRouteImport,
} as any)
const MilestonesRoute = MilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsPipelineRoute = ProjectsPipelineRouteImport.update({
  id: '/projects-pipeline',
  path: '/projects-pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteRoute = WebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-workspace': typeof AiWorkspaceRoute
  '/analytics': typeof AnalyticsRoute
  '/automation': typeof AutomationRoute
  '/calendar': typeof CalendarRoute
  '/conversations': typeof ConversationsRoute
  '/executive-dashboard': typeof ExecutiveDashboardRoute
  '/files': typeof FilesRoute
  '/game-dev': typeof GameDevRoute
  '/milestones': typeof MilestonesRoute
  '/projects-pipeline': typeof ProjectsPipelineRoute
  '/tasks': typeof TasksRoute
  '/website': typeof WebsiteRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/': typeof ClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-workspace': typeof AiWorkspaceRoute
  '/analytics': typeof AnalyticsRoute
  '/automation': typeof AutomationRoute
  '/calendar': typeof CalendarRoute
  '/conversations': typeof ConversationsRoute
  '/executive-dashboard': typeof ExecutiveDashboardRoute
  '/files': typeof FilesRoute
  '/game-dev': typeof GameDevRoute
  '/milestones': typeof MilestonesRoute
  '/projects-pipeline': typeof ProjectsPipelineRoute
  '/tasks': typeof TasksRoute
  '/website': typeof WebsiteRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients': typeof ClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-workspace': typeof AiWorkspaceRoute
  '/analytics': typeof AnalyticsRoute
  '/automation': typeof AutomationRoute
  '/calendar': typeof CalendarRoute
  '/conversations': typeof ConversationsRoute
  '/executive-dashboard': typeof ExecutiveDashboardRoute
  '/files': typeof FilesRoute
  '/game-dev': typeof GameDevRoute
  '/milestones': typeof MilestonesRoute
  '/projects-pipeline': typeof ProjectsPipelineRoute
  '/tasks': typeof TasksRoute
  '/website': typeof WebsiteRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/': typeof ClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-workspace'
    | '/analytics'
    | '/automation'
    | '/calendar'
    | '/conversations'
    | '/executive-dashboard'
    | '/files'
    | '/game-dev'
    | '/milestones'
    | '/projects-pipeline'
    | '/tasks'
    | '/website'
    | '/api/chat'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/clients/$clientId'
    | '/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-workspace'
    | '/analytics'
    | '/automation'
    | '/calendar'
    | '/conversations'
    | '/executive-dashboard'
    | '/files'
    | '/game-dev'
    | '/milestones'
    | '/projects-pipeline'
    | '/tasks'
    | '/website'
    | '/api/chat'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/clients/$clientId'
    | '/clients'
  id:
    | '__root__'
    | '/'
    | '/ai-workspace'
    | '/analytics'
    | '/automation'
    | '/calendar'
    | '/conversations'
    | '/executive-dashboard'
    | '/files'
    | '/game-dev'
    | '/milestones'
    | '/projects-pipeline'
    | '/tasks'
    | '/website'
    | '/api/chat'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/clients/$clientId'
    | '/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiWorkspaceRoute: typeof AiWorkspaceRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AutomationRoute: typeof AutomationRoute
  CalendarRoute: typeof CalendarRoute
  ConversationsRoute: typeof ConversationsRoute
  ExecutiveDashboardRoute: typeof ExecutiveDashboardRoute
  FilesRoute: typeof FilesRoute
  GameDevRoute: typeof GameDevRoute
  MilestonesRoute: typeof MilestonesRoute
  ProjectsPipelineRoute: typeof ProjectsPipelineRoute
  TasksRoute: typeof TasksRoute
  WebsiteRoute: typeof WebsiteRoute
  ApiChatRoute: typeof ApiChatRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-workspace': {
      id: '/ai-workspace'
      path: '/ai-workspace'
      fullPath: '/ai-workspace'
      preLoaderRoute: typeof AiWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive-dashboard': {
      id: '/executive-dashboard'
      path: '/executive-dashboard'
      fullPath: '/executive-dashboard'
      preLoaderRoute: typeof ExecutiveDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-dev': {
      id: '/game-dev'
      path: '/game-dev'
      fullPath: '/game-dev'
      preLoaderRoute: typeof GameDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milestones': {
      id: '/milestones'
      path: '/milestones'
      fullPath: '/milestones'
      preLoaderRoute: typeof MilestonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects-pipeline': {
      id: '/projects-pipeline'
      path: '/projects-pipeline'
      fullPath: '/projects-pipeline'
      preLoaderRoute: typeof ProjectsPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website': {
      id: '/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof WebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiWorkspaceRoute: AiWorkspaceRoute,
  AnalyticsRoute: AnalyticsRoute,
  AutomationRoute: AutomationRoute,
  CalendarRoute: CalendarRoute,
  ConversationsRoute: ConversationsRoute,
  ExecutiveDashboardRoute: ExecutiveDashboardRoute,
  FilesRoute: FilesRoute,
  GameDevRoute: GameDevRoute,
  MilestonesRoute: MilestonesRoute,
  ProjectsPipelineRoute: ProjectsPipelineRoute,
  TasksRoute: TasksRoute,
  WebsiteRoute: WebsiteRoute,
  ApiChatRoute: ApiChatRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsIndexRoute: ClientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
